### ISSUE TITLE
Lazy pull request

### ISSUE THREAD

**Issue by dev4dev** [mattcomi/ReflectedStringConvertible#1]
Hi, I think it could be reduced a little bit

``` swift
extension ReflectedStringConvertible {
    public var description: String {
        let mirror = Mirror(reflecting: self)

        var str = "\(mirror.subjectType)("

        str += mirror.children.map { label, value in
            "\(label): \(value)"
        }.joinWithSeparator(", ")

        str += ")"

        return str
    }
}
```

**Comment by mattcomi** [comment]
This is pretty good, and a lot faster than the original implementation but it has a problem: the map parameter `label` is a `String?` and so, the interpolated string looks like `Optional(whatever)`. I have a version that uses flatMap and fewer string concatenations that I will be committing soon.
