### ISSUE TITLE
Swift 3 compatibility

### ISSUE THREAD

**Issue by lfarah** [mattcomi/ReflectedStringConvertible#5]
Hey, I'd love to see this lib available in Swift 3 so I can implement it in my project.

Thanks 😄

**Comment by muescha** [comment]
+1

**Comment by esetnik** [comment]
I created #6 which has swift 3 support. If you want to use it before @mattcomi accepts the PR you can use

```
pod 'ReflectedStringConvertible', :git => 'https://github.com/esetnik/ReflectedStringConvertible.git'
```

**Comment by lfarah** [comment]
thanks, @esetnik!

**Comment by mattcomi** [comment]
Merged!
